### ISSUE TITLE
Remove Subnet resource on next major release

### ISSUE THREAD

**Issue by zhangyoufu** [pulumi/pulumi-alicloud#263]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

It seems that resource [Switch](https://www.pulumi.com/registry/packages/alicloud/api-docs/vpc/switch/) and [Subnet](https://www.pulumi.com/registry/packages/alicloud/api-docs/vpc/subnet/) refer the same thing, `alicloud_vswitch` in Terraform.
And documentation for `Subnet` resource is incomplete.

If Pulumi intentionally use `Subnet` as an "alias" for `Switch`, the documentation should be fixed, and improved by saying that both resource type do the same thing, except different urn.

Personally, I would prefer removing `Subnet` resource from alicloud provider, to stay in consistent with alicloud terms.

**Comment by guineveresaenger** [comment]
Hi @zhangyoufu - thank you for reporting this!

It does appear that the Subnet resource is either deprecated or never existed. This should get fixed with the next release of this provider in #262.

Thank you and apologies for any confusion.

**Comment by zhangyoufu** [comment]
Hi @guineveresaenger 

#262 (closed) was superseded by #278 (merged), but this issue still exists. Please take a look. Thanks.

**Comment by guineveresaenger** [comment]
Hi @zhangyoufu - I [added a deprecation message](https://github.com/pulumi/pulumi-alicloud/pull/304) to the Subnet resource. Because removing this is a breaking schema change, we will remove it on the next major release of this provider.
